package hibernate;
// Generated 2018-10-9 14:32:26 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;

/**
 * Seller generated by hbm2java
 */
public class Seller implements java.io.Serializable {

	private BigDecimal id;
	private Seller seller;
	private String name;
	private String tel;
	private String address;
	private String website;
	private String star;
	private String business;

	public Seller() {
	}

	public Seller(Seller seller) {
		this.seller = seller;
	}

	public Seller(Seller seller, String name, String tel, String address, String website, String star, String business
			) {
		this.seller = seller;
		this.name = name;
		this.tel = tel;
		this.address = address;
		this.website = website;
		this.star = star;
		this.business = business;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getStar() {
		return this.star;
	}

	public void setStar(String star) {
		this.star = star;
	}

	public String getBusiness() {
		return this.business;
	}

	public void setBusiness(String business) {
		this.business = business;
	}

	public Seller getSeller() {
		return this.seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

}
