package hibernate;
// Generated 2018-10-9 14:32:26 by Hibernate Tools 5.3.0.Beta2

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private long sid;
	private String sname;
	private String sex;
	private Long gid;

	public Student() {
	}

	public Student(long sid, String sname) {
		this.sid = sid;
		this.sname = sname;
	}

	public Student(long sid, String sname, String sex, Long gid) {
		this.sid = sid;
		this.sname = sname;
		this.sex = sex;
		this.gid = gid;
	}

	public long getSid() {
		return this.sid;
	}

	public void setSid(long sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Long getGid() {
		return this.gid;
	}

	public void setGid(Long gid) {
		this.gid = gid;
	}

}
